### ISSUE TITLE
Why merge dwm and dwmblocks?

### ISSUE THREAD

**Issue by Buttars** [PhyTech-R0/dwm-phyOS#16]
Was there a reason to merge the two? They're two separate pieces of software that do two different things. By merging them you've violated the suckless methodology. 

Is there a technical reason to doing this other than "only installing one thing?" 

It's a shame because I want to use your flavor of dwmblocks but not dwm and now that is not possible.

**Comment by r0-zero** [comment]
So you talk mean, I will be mean too. First of all "every program needs to have 1 purpose" is not suckless philosophy, its Unix philosophy which suckless follows. I dont think you know C or makefiles, because if you just took even a small peek in Makefiles, you can see that dwmblocks and dwm are 2 seperate binary executable programs. Copy dwmblocks.c and dwmblocks.h then write your own makefile.

**Comment by landon-buttars-wgu** [comment]
If you found my comments mean that's on you. After reviewing your socials I see you respond similarly to anyone with similar critiques.

You've made your software much more difficult to extend from it's original form. 

If it is two separate builds have them in two repos and have a command pull them separately since they're separate software. This is how every other flavor of dwm+blocks does it. 

Even if I were to follow your instructions to copy those files and write a makefile for them, that would result in the inability to pull changes from this branch in the future.

**Comment by explosion-mental** [comment]
I actually have merged dwmblocks into dwm itself. [some reasons](https://explosion-mental.codeberg.page/topics/demwm.html#Status-Text)

And some thoughts:
- the unix idea is fine. This generates such need to IPC in between: pipes!!11 `|`. Having dwm read a fifo to display the status would be okaish (maybe more unix) but def not suckless.
- Then, why even have a bar? One reason I believe dwm has an status bar is because.. it needs one. A 'killer' or 'unique' or 'original' or just clever idea is the tags system.
- So, either make a simple bar that displays tags (the useful thing) or make your whole window manager ewmh compliant to allow external bars to werk. dwm tag functionality wouldnt play well on that i think
...

I think this could be like comparing bspwm and dwm.
both 'suckless', but muh lines of code!!11 (dwm is overall simpler)
