### ISSUE TITLE
patch request for png in statusbar

### ISSUE THREAD

**Issue by siduck** [PhyTech-R0/dwm-phyOS#2]
Hi there! great build. Btw could you share the patch needed for having png in the statusbar?

**Comment by r0-zero** [comment]
Thank you!! I write it on my patched dwm build therefore i could not create a patch file. When i have time, i will write it on base dwm and share it afterwards.

**Comment by siduck** [comment]
Offtopic! How much of C I must know to make stuff for dwm? any additional knowledge required?

**Comment by r0-zero** [comment]
Umm, first the C basics of course (R&K C book is really good, it is nearly 400 pages and shows the insights of language, however note that it is older C, uses octal system etc). Good memory management, where to use static variables, when to use unions, how to implement enum's well is enough i think. As an addition to basic C, suckless mostly uses old libraries, like using old X11 instead of newer version xcb. After basics, i think just learn X11/Xft and utf-8 decoding. X11 itself is really huge, and really painful in learning because of confusing documentation and lack of tutorials. And i really love your dwm build/dots, and if you want to make dwm prettier i suggest you to learn 2 extra libraries, which are cairo and a little bit of xcb. Xcb has some extra features than X11, which can be pretty useful, but you don't need to deep dive much. Just learn extra features of xcb missing in X11, that will be more than plenty enough. As for cairo, you can think of it as a top layer ui tool for X11. Unfortunately, base X11 doesn't support anything other than drawing lines, rectangles and arcs. With cairo extension, you can add proper good looking animations / rounding corners etc.

**Comment by siduck** [comment]
really helpful! thanks :D

**Comment by r0-zero** [comment]
Glad if i could help!!

**Comment by r0-zero** [comment]
@siduck Hey! I could not make that icon patch, this is not about that. I really like your ideas about ui and design, how about together making the coolest dwm? You give the ideas, I implement them.

**Comment by siduck** [comment]
> @siduck Hey! I could not make that icon patch, this is not about that. I really like your ideas about ui and design, how about together making the coolest dwm? You give the ideas, I implement them.

sounds good! I had the exact idea before xD but was  quite hesitant to ask it

**Comment by r0-zero** [comment]
You shouldve aske :p can you add me on discord?
FTLabs#2188
