### ISSUE TITLE
Wanted to implement your version of dwmblocks

### ISSUE THREAD

**Issue by hoshiya4522** [PhyTech-R0/dwm-phyOS#7]
First of all, great build of DWM and DWMBlocks. 
I really wanted to implement your version of dwmblocks but, I am having a hard time to do so. Could you please tell me how did you implement the clickability into dwm.c?
Did you use [statuscmd with signals](https://dwm.suckless.org/patches/statuscmd/) or something?

**Comment by r0-zero** [comment]
Thank you for your comment. Yes, it is using that patch. Statuscmd signal will make the bar clickable, but since this fork is using png & X11 drawn seperators lots of functions have changed. To use base dwmblocks, just add statuscmd signal patch & torrinfail fork of dwmblocks. Then you will be good to go. If you want to implement this one, I can give you hints about which functions to change & implement, but your config file needs to change too, as well as 5-6 functions.
