### ISSUE TITLE
Suggestion for eyecandy.

### ISSUE THREAD

**Issue by hoshiya4522** [PhyTech-R0/dwm-phyOS#8]
Dear Phy,
Great project with great eye candy but I have a suggestion to enhance the feel.

I hope you have heard of [Elkowar's Wacky Widgets (eww)](https://github.com/elkowar/eww). I think you have seen (elenapan's rice)[https://old.reddit.com/r/unixporn/comments/hpakeu/awesome_afternoon_in_a_perfect_world/] on unixporn. The dashboard widget on the bottom picture is made with eww. It would be a great addition to your dwm build.

El Psy Kongroo.

**Comment by r0-zero** [comment]
Actually I have thinked about including eww, but I saw that it is mostly used for functionality for opening wifi application or handling sounds-brightness etc. Since top statusbar is clickable and can open applications, I did not include it. Likewise calendar is also available through clicking the bar, but if there is more request I will include it! Maybe if making a networkmanager menu is possible with eww, I will try to do it. Thank you for your comment btw!

**Comment by xd003** [comment]
@FT-Labs  Please do include any good looking & light weight networkmanager menu & brightness control in the bar ( or atleast have the option to enable it if not by default ) . Eww definitely looks pretty damm good , although i am not  familar with WM's so don't know how it goes with PhyOS's current setup

**Comment by r0-zero** [comment]
@xd003 I am not planning to actually. It uses simple nmtui (I think it is good enough for now), and pulsemixer for sound. Also sound+brightness are already bounded to kesy, scripts & notifications in center, which is okay I think.
